import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {resolve} from 'node:path';import {createApp} from '../server/app.mjs';import {openDatabase} from '../server/db.mjs';import {id,passwordHash,hash} from '../server/security.mjs';
test('role isolation, live messages, guest recovery, projects, requests, invoices, invitations and persistence',async()=>{
 const folder=mkdtempSync(resolve(tmpdir(),'velcodes-test-')),config={databasePath:resolve(folder,'test.sqlite'),origin:'http://localhost:4180',production:false,publicDir:resolve('public'),siteDir:resolve('../dist'),adminEmail:'admin@example.test',notificationEmail:'admin@example.test',emailProvider:'disabled',trustProxy:false},app=createApp(config);await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+app.server.address().port,accounts={};
 for(const [name,role] of [['admin','admin'],['alice','client'],['bob','client'],['worker','worker'],['otherworker','worker']]){const uid=id();app.db.prepare('INSERT INTO users(id,email,name,password,role,verified,created_at) VALUES(?,?,?,?,?,1,?)').run(uid,name+'@example.test',name,passwordHash('test-password-long-123'),role,new Date().toISOString());accounts[name]={id:uid}}
 async function req(path,{who,method='GET',body,guest,origin=config.origin}={}){const r=await fetch(base+'/api'+path,{method,headers:{...(who?{Cookie:accounts[who].cookie}:{}),...(guest?{Authorization:'Bearer '+guest}:{}),...(body?{'Content-Type':'application/json',Origin:origin}:{})},body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json(),headers:r.headers}}
 try{
 for(const name of Object.keys(accounts)){const r=await req('/auth/login',{method:'POST',body:{email:name+'@example.test',password:'test-password-long-123'}});assert.equal(r.status,200);accounts[name].cookie=r.headers.get('set-cookie').split(';')[0];assert.match(r.headers.get('set-cookie'),/HttpOnly/)}
 assert.equal((await req('/overview')).status,401);
 assert.equal((await req('/projects',{who:'alice',method:'POST',body:{name:'malicious'}})).status,403);
 assert.equal((await req('/projects',{who:'admin',method:'POST',origin:'http://evil.test',body:{}})).status,403);
 const made=await req('/projects',{who:'admin',method:'POST',body:{name:'Client workspace',description:'A scoped project.',clientId:accounts.alice.id,dueDate:'2027-03-01'}});assert.equal(made.status,201);const pid=made.body.id;
 assert.equal((await req('/projects/'+pid,{who:'alice'})).status,200);assert.equal((await req('/projects/'+pid,{who:'bob'})).status,404);assert.equal((await req('/projects/'+pid,{who:'worker'})).status,404);
 assert.equal((await req('/projects/'+pid+'/assignments',{who:'admin',method:'PUT',body:{userIds:[accounts.worker.id]}})).status,200);assert.equal((await req('/projects/'+pid,{who:'worker'})).status,200);assert.equal((await req('/projects/'+pid,{who:'otherworker'})).status,404);
 assert.equal((await req('/projects/'+pid,{who:'worker',method:'PATCH',body:{status:'in_progress',progress:35}})).status,200);assert.equal((await req('/projects/'+pid,{who:'alice',method:'PATCH',body:{status:'complete',progress:100}})).status,403);
 const detail=(await req('/projects/'+pid,{who:'alice'})).body;assert.equal(detail.team[0].name,'worker');assert.equal(detail.project.progress,35);const cid=detail.conversation.id;
 assert.equal((await req('/conversations/'+cid,{who:'bob'})).status,404);
 const msg={body:'Please update the homepage.',clientKey:'alice-1'};assert.equal((await req('/conversations/'+cid+'/messages',{who:'alice',method:'POST',body:msg})).status,201);assert.equal((await req('/conversations/'+cid+'/messages',{who:'alice',method:'POST',body:msg})).status,200);assert.equal((await req('/conversations/'+cid,{who:'worker'})).body.messages.length,1);
 assert.equal((await req('/projects/'+pid+'/requests',{who:'alice',method:'POST',body:{title:'Add a section',body:'Please include our team.'}})).status,201);const rid=(await req('/projects/'+pid,{who:'worker'})).body.requests[0].id;assert.equal((await req('/requests/'+rid,{who:'bob',method:'PATCH',body:{status:'approved'}})).status,404);assert.equal((await req('/requests/'+rid,{who:'worker',method:'PATCH',body:{status:'reviewing'}})).status,200);
 const inv=await req('/invoices',{who:'admin',method:'POST',body:{projectId:pid,number:'TEST-001',description:'Development milestone',amountCents:125000,currency:'USD',dueDate:'2027-04-01',status:'draft'}});assert.equal(inv.status,201);const iid=inv.body.id;assert.equal((await req('/invoices/'+iid,{who:'alice'})).status,404);assert.equal((await req('/invoices/'+iid,{who:'worker'})).status,404);assert.equal((await req('/invoices/'+iid,{who:'admin',method:'PATCH',body:{status:'issued'}})).status,200);assert.equal((await req('/invoices/'+iid,{who:'alice'})).body.invoice.amount_cents,125000);assert.equal((await req('/invoices/'+iid,{who:'bob'})).status,404);assert.equal((await req('/invoices/'+iid,{who:'alice',method:'PATCH',body:{status:'paid'}})).status,403);
 const guest=await req('/guest/session',{method:'POST',body:{name:'Visitor',email:'visitor@example.test'}});assert.equal(guest.status,201);const gt=guest.body.token,gc=guest.body.conversationId;assert.equal((await req('/conversations/'+gc)).status,404);assert.equal((await req('/conversations/'+gc,{who:'worker'})).status,404);assert.equal((await req('/conversations/'+gc+'/messages',{guest:gt,method:'POST',body:{body:'I need a new site.',clientKey:'guest-1'}})).status,201);assert.equal((await req('/guest/me',{guest:gt})).body.conversation.id,gc);assert.equal((await req('/conversations/'+gc,{who:'admin'})).body.messages[0].body,'I need a new site.');
 assert.equal((await req('/conversations/'+gc+'/messages',{who:'admin',method:'POST',body:{body:'Happy to help.',clientKey:'reply-1'}})).status,201);assert.equal((await req('/conversations/'+gc,{guest:gt})).body.messages.length,2);
 const controller=new AbortController(),stream=await fetch(base+'/api/events',{headers:{Authorization:'Bearer '+gt},signal:controller.signal});assert.equal(stream.status,200);const reader=stream.body.getReader();assert.match(new TextDecoder().decode((await reader.read()).value),/connected/);await req('/conversations/'+gc+'/messages',{who:'admin',method:'POST',body:{body:'What are your goals?',clientKey:'reply-2'}});assert.match(new TextDecoder().decode((await reader.read()).value),/refresh/);controller.abort();
 const invite=await req('/team/invite',{who:'admin',method:'POST',body:{name:'Invited client',email:'invited@example.test',role:'client'}});assert.equal(invite.status,201);const it=new URL(invite.body.inviteUrl).searchParams.get('token');assert.equal((await req('/auth/redeem',{method:'POST',body:{token:it,password:'new-long-password-123'}})).status,200);assert.equal((await req('/auth/redeem',{method:'POST',body:{token:it,password:'new-long-password-123'}})).status,400);assert.equal((await req('/team/invite',{who:'alice',method:'POST',body:{name:'attacker',email:'x@example.test',role:'admin'}})).status,403);
 assert.equal((await req('/team/'+accounts.worker.id,{who:'admin',method:'PATCH',body:{active:false}})).status,200);assert.equal((await req('/overview',{who:'worker'})).status,401);assert.equal(app.db.prepare("SELECT count(*) n FROM email_outbox WHERE status='pending'").get().n,3);assert.equal(app.db.prepare('SELECT token_hash FROM guests WHERE id=(SELECT guest_id FROM conversations WHERE id=?)').get(gc).token_hash,hash(gt));
 assert.equal((await req('/conversations/claim',{who:'alice',method:'POST',body:{token:gt}})).status,200);assert.equal((await req('/conversations/'+gc,{guest:gt})).status,404);assert.equal((await req('/conversations/'+gc,{who:'alice'})).status,200);assert.equal((await req('/conversations/'+gc,{who:'bob'})).status,404);
 await app.close();const reopened=openDatabase(config.databasePath);assert.equal(reopened.prepare('SELECT count(*) n FROM messages').get().n,4);reopened.close();
 }finally{if(app.server.listening)await app.close();rmSync(folder,{recursive:true,force:true})}
});
