import {createServer} from 'node:http';
import {readFile,stat} from 'node:fs/promises';
import {resolve,extname,sep} from 'node:path';
import {openDatabase,transaction} from './db.mjs';
import {id,token,hash,passwordHash,passwordValid,validPassword,publicUser,cookies,email,text,rateLimit} from './security.mjs';
import {enqueue,deliver} from './mail.mjs';
const now=()=>new Date().toISOString();
const failure=(status,message)=>Object.assign(new Error(message),{status});
const date=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v));
const safeUserFields='id,email,name,role,verified,active,created_at';
export function createApp(config){
 const db=openDatabase(config.databasePath),listeners=new Set();let sending=false;
 const adminIds=()=>db.prepare("SELECT id FROM users WHERE role='admin' AND active=1").all().map(x=>x.id);
 function emit(userIds=[],guestId=null){for(const l of listeners)if(userIds.includes(l.userId)||(guestId&&guestId===l.guestId))l.res.write('event: refresh\ndata: {}\n\n')}
 function projectPeople(pid){const p=db.prepare('SELECT client_id FROM projects WHERE id=?').get(pid);return [...adminIds(),...(p?[p.client_id]:[]),...db.prepare('SELECT user_id FROM assignments WHERE project_id=?').all(pid).map(x=>x.user_id)]}
 function changedConversation(c){emit(c.project_id?projectPeople(c.project_id):[...adminIds(),c.client_id].filter(Boolean),c.guest_id)}
 function audit(pid,u,body){db.prepare('INSERT INTO activity(id,project_id,actor_id,body,created_at) VALUES(?,?,?,?,?)').run(id(),pid,u.id,body,now())}
 function userFrom(req){const raw=cookies(req).velcodes_session;if(!raw)return null;return db.prepare('SELECT u.* FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>? AND u.active=1').get(hash(raw),Date.now())||null}
 function guestFrom(req){const raw=(req.headers.authorization||'').replace(/^Bearer /,'');if(!/^[a-f0-9]{64}$/.test(raw))return null;return db.prepare('SELECT * FROM guests WHERE token_hash=? AND expires_at>?').get(hash(raw),Date.now())||null}
 function requireUser(req){const u=userFrom(req);if(!u)throw failure(401,'Please sign in to continue.');return u}
 function ready(req){const u=requireUser(req);if(!u.verified)throw failure(403,'Verify your email before opening the workspace.');if(u.must_change)throw failure(403,'Change your temporary password before continuing.');return u}
 function requireAdmin(u){if(u.role!=='admin')throw failure(403,'Administrator access is required.')}
 function projectFor(u,pid){const p=db.prepare('SELECT * FROM projects WHERE id=?').get(pid);if(!p||!(u.role==='admin'||p.client_id===u.id||(u.role==='worker'&&db.prepare('SELECT 1 FROM assignments WHERE project_id=? AND user_id=?').get(pid,u.id))))throw failure(404,'Project not found.');return p}
 function conversationFor(u,g,cid){const c=db.prepare('SELECT * FROM conversations WHERE id=?').get(cid);if(!c)throw failure(404,'Conversation not found.');if(g&&c.guest_id===g.id&&!c.client_id)return c;if(u&&(u.role==='admin'||c.client_id===u.id))return c;if(u&&c.project_id){projectFor(u,c.project_id);return c}throw failure(404,'Conversation not found.')}
 function listProjects(u){if(u.role==='admin')return db.prepare('SELECT p.*,u.name client_name FROM projects p JOIN users u ON u.id=p.client_id ORDER BY p.updated_at DESC').all();return db.prepare('SELECT DISTINCT p.*,u.name client_name FROM projects p JOIN users u ON u.id=p.client_id LEFT JOIN assignments a ON a.project_id=p.id WHERE p.client_id=? OR (a.user_id=? AND ?=\'worker\') ORDER BY p.updated_at DESC').all(u.id,u.id,u.role)}
 function listConversations(u){return db.prepare(`SELECT c.*,COALESCE(u.name,g.name,'Visitor') contact_name,COALESCE(u.email,g.email,'') contact_email,(SELECT body FROM messages WHERE conversation_id=c.id ORDER BY created_at DESC,rowid DESC LIMIT 1) last_message FROM conversations c LEFT JOIN users u ON c.client_id=u.id LEFT JOIN guests g ON c.guest_id=g.id WHERE ?='admin' OR c.client_id=? OR (c.project_id IN (SELECT project_id FROM assignments WHERE user_id=?) AND ?='worker') ORDER BY c.updated_at DESC`).all(u.role,u.id,u.id,u.role)}
 function session(res,u){const raw=token();db.prepare('INSERT INTO sessions(token_hash,user_id,expires_at,created_at) VALUES(?,?,?,?)').run(hash(raw),u.id,Date.now()+7*86400000,Date.now());res.setHeader('Set-Cookie',`velcodes_session=${raw}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800${config.production?'; Secure':''}`)}
 function authToken(u,kind){const raw=token();db.prepare('DELETE FROM auth_tokens WHERE user_id=? AND kind=?').run(u.id,kind);db.prepare('INSERT INTO auth_tokens(token_hash,user_id,kind,expires_at) VALUES(?,?,?,?)').run(hash(raw),u.id,kind,Date.now()+(kind==='invite'?7*86400000:3600000));return config.origin+'/portal/?action='+kind+'&token='+raw}
 function json(res,data,status=200){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))}
 async function body(req){let total=0,data='';for await(const part of req){total+=part.length;if(total>20000)throw failure(413,'This request is too large.');data+=part}try{return JSON.parse(data||'{}')}catch{throw failure(400,'Invalid request.')}}
 function isRead(req){return req.method==='GET'||req.method==='HEAD'}
 async function handle(req,res){
  res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Frame-Options','DENY');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');if(config.production)res.setHeader('Strict-Transport-Security','max-age=31536000');
  const url=new URL(req.url,config.origin),path=url.pathname,ip=config.trustProxy?(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim():req.socket.remoteAddress||'unknown';
  try{
   if(path==='/portal'){res.writeHead(302,{Location:'/portal/'});res.end();return}
   if(path==='/api/health')return json(res,{ok:true});
   if(path.startsWith('/api/')){
    if(!rateLimit(db,'ip:'+ip,300))throw failure(429,'Too many requests. Please wait a minute.');
    if(!isRead(req)){if(req.headers.origin!==config.origin)throw failure(403,'This request must come from the Velcodes portal.');if(!String(req.headers['content-type']).startsWith('application/json'))throw failure(415,'Use a JSON request.');}
    if(path==='/api/auth/me'&&req.method==='GET'){const u=userFrom(req);return json(res,{user:u?publicUser(u):null,emailEnabled:config.emailProvider==='resend'&&!!config.resendKey})}
    if(path.startsWith('/api/auth/')&&!isRead(req)&&!rateLimit(db,'auth:'+ip,15,15*60000))throw failure(429,'Too many sign-in attempts. Please try again later.');
    if(path==='/api/auth/register'&&req.method==='POST'){
     const b=await body(req),em=String(b.email||'').trim().toLowerCase();if(!email(em)||!text(b.name,100)||!validPassword(b.password))throw failure(400,'Enter your name, a valid email and a password of 12–128 characters.');
     if(em===config.adminEmail||db.prepare('SELECT id FROM users WHERE email=?').get(em))throw failure(409,'This email cannot be registered. Try signing in or resetting your password.');
     const uid=id();transaction(db,()=>{db.prepare('INSERT INTO users(id,email,name,password,created_at) VALUES(?,?,?,?,?)').run(uid,em,b.name.trim(),passwordHash(b.password),now());const u=db.prepare('SELECT * FROM users WHERE id=?').get(uid);enqueue(db,em,'Verify your Velcodes account','Confirm your email to access your workspace:\n'+authToken(u,'verify')+'\nThis link expires in one hour.');});
     return json(res,{message:config.emailProvider==='resend'?'Check your email for the verification link.':'Your account is created. Email verification is pending until Velcodes enables email delivery. Contact info@velcodes.com for help.'},201)
    }
    if(path==='/api/auth/login'&&req.method==='POST'){
     const b=await body(req);if(typeof b.password!=='string'||b.password.length>128)throw failure(400,'Invalid sign-in details.');const u=db.prepare('SELECT * FROM users WHERE email=?').get(String(b.email||'').trim().toLowerCase());const dummy='7dde2f7fdb5de22420e3503578805831:'+ '00'.repeat(64);const valid=passwordValid(b.password,u?.password||dummy);if(!u||!valid||!u.active)throw failure(401,'Email or password is incorrect.');if(!u.verified)throw failure(403,'Verify your email before signing in. If needed, use Forgot password to request a new email link.');session(res,u);return json(res,{user:publicUser(u)})
    }
    if(path==='/api/auth/logout'&&req.method==='POST'){const raw=cookies(req).velcodes_session;if(raw)db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hash(raw));res.setHeader('Set-Cookie',`velcodes_session=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0${config.production?'; Secure':''}`);return json(res,{ok:true})}
    if(path==='/api/auth/forgot'&&req.method==='POST'){const b=await body(req),u=db.prepare('SELECT * FROM users WHERE email=? AND active=1').get(String(b.email||'').trim().toLowerCase());if(u)enqueue(db,u.email,'Reset your Velcodes password','Reset your password using this link:\n'+authToken(u,'reset')+'\nThis link expires in one hour.');return json(res,{message:'If that account exists, a password reset email will be queued. If email delivery is unavailable, contact info@velcodes.com.'})}
    if(path==='/api/auth/redeem'&&req.method==='POST'){const b=await body(req);if(typeof b.token!=='string'||b.token.length!==64)throw failure(400,'This link is invalid or expired.');const t=db.prepare('SELECT * FROM auth_tokens WHERE token_hash=? AND expires_at>?').get(hash(b.token),Date.now());if(!t)throw failure(400,'This link is invalid or expired.');if(t.kind!=='verify'&&!validPassword(b.password))throw failure(400,'Choose a password of 12–128 characters.');transaction(db,()=>{if(t.kind==='verify')db.prepare('UPDATE users SET verified=1 WHERE id=?').run(t.user_id);else db.prepare('UPDATE users SET password=?,verified=1,must_change=0 WHERE id=?').run(passwordHash(b.password),t.user_id);db.prepare('DELETE FROM auth_tokens WHERE user_id=?').run(t.user_id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(t.user_id)});return json(res,{message:'Your account is ready. You can sign in now.'})}
    if(path==='/api/auth/password'&&req.method==='POST'){const u=requireUser(req),b=await body(req);if(typeof b.current!=='string'||!passwordValid(b.current,u.password))throw failure(400,'Your current password is incorrect.');if(!validPassword(b.password))throw failure(400,'Choose a password of 12–128 characters.');transaction(db,()=>{db.prepare('UPDATE users SET password=?,must_change=0 WHERE id=?').run(passwordHash(b.password),u.id);db.prepare('DELETE FROM sessions WHERE user_id=?').run(u.id)});session(res,u);return json(res,{ok:true})}
    if(path==='/api/guest/session'&&req.method==='POST'){
     if(!rateLimit(db,'guest-create:'+ip,8,3600000))throw failure(429,'Please wait before starting another conversation.');const b=await body(req);if(b.email&&!email(b.email))throw failure(400,'Please enter a valid email or leave it blank.');const raw=token(),gid=id(),cid=id();transaction(db,()=>{db.prepare('INSERT INTO guests(token_hash,id,name,email,expires_at,created_at) VALUES(?,?,?,?,?,?)').run(hash(raw),gid,(typeof b.name==='string'?b.name.trim().slice(0,100):'')||'Visitor',String(b.email||'').trim().toLowerCase(),Date.now()+180*86400000,now());db.prepare('INSERT INTO conversations(id,guest_id,subject,created_at,updated_at) VALUES(?,?,?,?,?)').run(cid,gid,'Website enquiry',now(),now())});return json(res,{token:raw,conversationId:cid},201)
    }
    if(path==='/api/guest/me'&&req.method==='GET'){const g=guestFrom(req);if(!g)throw failure(401,'Start a new conversation to continue.');return json(res,{conversation:db.prepare('SELECT id,subject,status FROM conversations WHERE guest_id=? AND client_id IS NULL ORDER BY created_at LIMIT 1').get(g.id)})}
    if(path==='/api/events'&&req.method==='GET'){
     const u=userFrom(req),g=guestFrom(req);if((!u||!u.verified||u.must_change)&&!g)throw failure(401,'Please sign in.');if([...listeners].filter(l=>l.userId===u?.id&&l.guestId===g?.id).length>=5)throw failure(429,'Too many live connections.');
     res.writeHead(200,{'Content-Type':'text/event-stream','Cache-Control':'no-store','Connection':'keep-alive','X-Accel-Buffering':'no'});res.write('event: connected\ndata: {}\n\n');const l={res,userId:u?.id,guestId:g?.id};listeners.add(l);const heartbeat=setInterval(()=>{if((u&&!userFrom(req))||(g&&!guestFrom(req))){res.end();return}res.write(': heartbeat\n\n')},20000);req.on('close',()=>{clearInterval(heartbeat);listeners.delete(l)});return
    }
    const cm=path.match(/^\/api\/conversations\/([a-f0-9]+)(\/messages)?$/);
    if(cm){const u=userFrom(req),g=guestFrom(req);if(u&&(!u.verified||u.must_change))throw failure(403,'Complete account setup first.');const c=conversationFor(u,g,cm[1]);
     if(req.method==='GET')return json(res,{conversation:c,messages:db.prepare('SELECT id,sender_id,guest_id,sender_name,body,created_at,client_key FROM (SELECT rowid AS position,* FROM messages WHERE conversation_id=? ORDER BY rowid DESC LIMIT 1000) ORDER BY position').all(c.id)});
     if(req.method==='POST'&&cm[2]){if(c.status==='closed')throw failure(409,'This conversation is closed. Start a new conversation or ask your team to reopen it.');if(!rateLimit(db,'message:'+(u?.id||g?.id),30,60000))throw failure(429,'Please slow down before sending more messages.');const b=await body(req);if(!text(b.body,4000)||!text(b.clientKey,100))throw failure(400,'Write a message of up to 4,000 characters.');if(db.prepare('SELECT id FROM messages WHERE conversation_id=? AND client_key=?').get(c.id,b.clientKey))return json(res,{ok:true});
      transaction(db,()=>{db.prepare('INSERT INTO messages(id,conversation_id,sender_id,guest_id,sender_name,body,client_key,created_at) VALUES(?,?,?,?,?,?,?,?)').run(id(),c.id,u?.id||null,u?null:g.id,u?.name||g.name,b.body.trim(),b.clientKey,now());db.prepare('UPDATE conversations SET updated_at=? WHERE id=?').run(now(),c.id);if(!u||u.role==='client')enqueue(db,config.notificationEmail,'New Velcodes message — '+c.subject,`${u?.name||g.name} ${u?.email||g.email||'(no email supplied)'}\n\n${b.body.trim()}\n\nOpen the conversation: ${config.origin}/portal/#messages/${c.id}`);});changedConversation(c);return json(res,{ok:true},201)
     }
     if(req.method==='PATCH'){const actor=ready(req);requireAdmin(actor);const b=await body(req);if(!['open','closed'].includes(b.status))throw failure(400,'Invalid conversation status.');db.prepare('UPDATE conversations SET status=?,updated_at=? WHERE id=?').run(b.status,now(),c.id);changedConversation(c);return json(res,{ok:true})}
    }
    const u=ready(req);
    if(path==='/api/overview'&&req.method==='GET'){const projects=listProjects(u),invoices=u.role==='worker'?[]:db.prepare("SELECT * FROM invoices WHERE (?='admin' OR client_id=?) AND (?='admin' OR status!='draft') ORDER BY created_at DESC").all(u.role,u.id,u.role);return json(res,{user:publicUser(u),projects,invoices,conversations:listConversations(u),email:u.role==='admin'?{enabled:config.emailProvider==='resend'&&!!config.resendKey,pending:db.prepare("SELECT count(*) n FROM email_outbox WHERE status='pending'").get().n,failed:db.prepare("SELECT count(*) n FROM email_outbox WHERE status='failed'").get().n}:null})}
    if(path==='/api/conversations/claim'&&req.method==='POST'){if(u.role!=='client')throw failure(403,'Only client accounts can claim visitor conversations.');const b=await body(req);if(typeof b.token!=='string'||!/^[a-f0-9]{64}$/.test(b.token))throw failure(400,'Invalid conversation access.');const g=db.prepare('SELECT * FROM guests WHERE token_hash=? AND expires_at>?').get(hash(b.token),Date.now());if(!g)throw failure(404,'Conversation access expired.');const c=db.prepare('SELECT * FROM conversations WHERE guest_id=? AND client_id IS NULL').get(g.id);if(!c)throw failure(404,'Conversation already linked or unavailable.');db.prepare('UPDATE conversations SET client_id=?,updated_at=? WHERE id=? AND client_id IS NULL').run(u.id,now(),c.id);emit([...adminIds(),u.id],g.id);return json(res,{ok:true,id:c.id})}
    if(path==='/api/conversations'&&req.method==='POST'){if(u.role==='worker')throw failure(403,'Use your assigned project conversations.');const b=await body(req),cid=id();db.prepare('INSERT INTO conversations(id,client_id,subject,created_at,updated_at) VALUES(?,?,?,?,?)').run(cid,u.id,text(b.subject,120)?b.subject.trim():'General enquiry',now(),now());emit([...adminIds(),u.id]);return json(res,{id:cid},201)}
    if(path==='/api/projects'&&req.method==='POST'){requireAdmin(u);const b=await body(req);if(!text(b.name,150)||!text(b.description,6000)||!db.prepare("SELECT id FROM users WHERE id=? AND role='client' AND active=1 AND verified=1").get(b.clientId)||b.dueDate&&!date(b.dueDate))throw failure(400,'Enter a project name, description, verified client and valid due date.');const pid=id(),cid=id();transaction(db,()=>{db.prepare('INSERT INTO projects(id,name,description,client_id,due_date,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(pid,b.name.trim(),b.description.trim(),b.clientId,b.dueDate||'',now(),now());db.prepare('INSERT INTO conversations(id,client_id,project_id,subject,created_at,updated_at) VALUES(?,?,?,?,?,?)').run(cid,b.clientId,pid,b.name.trim(),now(),now());audit(pid,u,'Project created')});emit(projectPeople(pid));return json(res,{id:pid},201)}
    const pm=path.match(/^\/api\/projects\/([a-f0-9]+)(?:\/(assignments|requests))?$/);
    if(pm){const p=projectFor(u,pm[1]);if(req.method==='GET')return json(res,{project:p,team:db.prepare('SELECT u.id,u.name,u.role FROM assignments a JOIN users u ON u.id=a.user_id WHERE a.project_id=? AND u.active=1').all(p.id),requests:db.prepare('SELECT r.*,u.name author_name FROM change_requests r JOIN users u ON u.id=r.author_id WHERE project_id=? ORDER BY r.created_at DESC').all(p.id),activity:db.prepare('SELECT a.*,u.name actor_name FROM activity a LEFT JOIN users u ON u.id=a.actor_id WHERE project_id=? ORDER BY a.created_at DESC,a.rowid DESC LIMIT 100').all(p.id),conversation:db.prepare('SELECT id FROM conversations WHERE project_id=?').get(p.id)});
     if(pm[2]==='assignments'&&req.method==='PUT'){requireAdmin(u);const b=await body(req);if(!Array.isArray(b.userIds)||b.userIds.length>50||b.userIds.some(x=>typeof x!=='string'||!db.prepare("SELECT id FROM users WHERE id=? AND role='worker' AND active=1 AND verified=1").get(x)))throw failure(400,'Select verified workers.');const previous=projectPeople(p.id);transaction(db,()=>{db.prepare('DELETE FROM assignments WHERE project_id=?').run(p.id);for(const uid of new Set(b.userIds))db.prepare('INSERT INTO assignments(project_id,user_id) VALUES(?,?)').run(p.id,uid);audit(p.id,u,'Project team updated')});emit([...previous,...projectPeople(p.id)]);return json(res,{ok:true})}
     if(pm[2]==='requests'&&req.method==='POST'){const b=await body(req);if(!text(b.title,180)||!text(b.body,6000))throw failure(400,'Add a title and describe your requested change.');transaction(db,()=>{db.prepare('INSERT INTO change_requests(id,project_id,author_id,title,body,created_at,updated_at) VALUES(?,?,?,?,?,?,?)').run(id(),p.id,u.id,b.title.trim(),b.body.trim(),now(),now());audit(p.id,u,'Change requested: '+b.title.trim())});emit(projectPeople(p.id));return json(res,{ok:true},201)}
     if(req.method==='PATCH'&&!pm[2]){if(u.role==='client')throw failure(403,'Only the project team can update progress.');const b=await body(req);if(!['planning','in_progress','review','complete','on_hold'].includes(b.status)||!Number.isInteger(b.progress)||b.progress<0||b.progress>100)throw failure(400,'Choose a status and progress from 0 to 100.');transaction(db,()=>{db.prepare('UPDATE projects SET status=?,progress=?,updated_at=? WHERE id=?').run(b.status,b.progress,now(),p.id);audit(p.id,u,`Progress updated: ${b.status.replaceAll('_',' ')} / ${b.progress}%`)});emit(projectPeople(p.id));return json(res,{ok:true})}
    }
    const rm=path.match(/^\/api\/requests\/([a-f0-9]+)$/);if(rm&&req.method==='PATCH'){const r=db.prepare('SELECT * FROM change_requests WHERE id=?').get(rm[1]);if(!r)throw failure(404,'Request not found.');projectFor(u,r.project_id);if(u.role==='client')throw failure(403,'Only the project team can update requests.');const b=await body(req);if(!['submitted','reviewing','approved','in_progress','completed','rejected'].includes(b.status))throw failure(400,'Invalid request status.');transaction(db,()=>{db.prepare('UPDATE change_requests SET status=?,updated_at=? WHERE id=?').run(b.status,now(),r.id);audit(r.project_id,u,'Change request updated: '+r.title+' / '+b.status.replaceAll('_',' '))});emit(projectPeople(r.project_id));return json(res,{ok:true})}
    if(path==='/api/invoices'&&req.method==='POST'){requireAdmin(u);const b=await body(req),p=projectFor(u,b.projectId);if(!text(b.number,60)||!text(b.description,2000)||!Number.isInteger(b.amountCents)||b.amountCents<=0||b.amountCents>100000000000||!['USD','GBP','EUR','PKR','AED','CAD','AUD'].includes(b.currency)||!date(b.dueDate)||!['draft','issued'].includes(b.status))throw failure(400,'Check the invoice number, amount, currency and due date.');if(db.prepare('SELECT id FROM invoices WHERE number=?').get(b.number.trim()))throw failure(409,'That invoice number is already in use.');const iid=id();transaction(db,()=>{db.prepare('INSERT INTO invoices(id,number,project_id,client_id,description,amount_cents,currency,due_date,status,notes,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(iid,b.number.trim(),p.id,p.client_id,b.description.trim(),b.amountCents,b.currency,b.dueDate,b.status,String(b.notes||'').slice(0,4000),now(),now());audit(p.id,u,'Invoice created: '+b.number.trim())});emit([...adminIds(),p.client_id]);return json(res,{id:iid},201)}
    const im=path.match(/^\/api\/invoices\/([a-f0-9]+)$/);if(im){const inv=db.prepare('SELECT i.*,p.name project_name,u.name client_name,u.email client_email FROM invoices i JOIN projects p ON p.id=i.project_id JOIN users u ON u.id=i.client_id WHERE i.id=?').get(im[1]);if(!inv||!(u.role==='admin'||(u.role==='client'&&inv.client_id===u.id&&inv.status!=='draft')))throw failure(404,'Invoice not found.');if(req.method==='GET')return json(res,{invoice:inv});if(req.method==='PATCH'){requireAdmin(u);const b=await body(req);const allowed={draft:['issued','void'],issued:['paid','void'],paid:[],void:[]};if(!allowed[inv.status].includes(b.status))throw failure(400,'This invoice status cannot be changed that way.');db.prepare('UPDATE invoices SET status=?,updated_at=? WHERE id=?').run(b.status,now(),inv.id);audit(inv.project_id,u,'Invoice '+inv.number+' marked '+b.status);emit([...adminIds(),inv.client_id]);return json(res,{ok:true})}}
    if(path==='/api/team'&&req.method==='GET'){requireAdmin(u);return json(res,{users:db.prepare('SELECT '+safeUserFields+' FROM users ORDER BY name').all()})}
    if(path==='/api/team/invite'&&req.method==='POST'){requireAdmin(u);const b=await body(req),em=String(b.email||'').trim().toLowerCase();if(!email(em)||!text(b.name,100)||!['client','worker'].includes(b.role))throw failure(400,'Enter a name, email and client or worker role.');if(db.prepare('SELECT id FROM users WHERE email=?').get(em))throw failure(409,'This email already has an account.');const uid=id();let link;transaction(db,()=>{db.prepare('INSERT INTO users(id,email,name,password,role,created_at) VALUES(?,?,?,?,?,?)').run(uid,em,b.name.trim(),passwordHash(token()),b.role,now());const invited=db.prepare('SELECT * FROM users WHERE id=?').get(uid);link=authToken(invited,'invite');enqueue(db,em,'Your Velcodes workspace invitation','You have been invited to Velcodes as a '+b.role+'. Set your password here:\n'+link+'\nThis link expires in seven days.')});emit(adminIds());return json(res,{ok:true,inviteUrl:link,emailEnabled:config.emailProvider==='resend'&&!!config.resendKey},201)}
    const um=path.match(/^\/api\/team\/([a-f0-9]+)$/);if(um&&req.method==='PATCH'){requireAdmin(u);const target=db.prepare('SELECT * FROM users WHERE id=?').get(um[1]);if(!target||target.role==='admin')throw failure(400,'Administrator accounts cannot be changed here.');const b=await body(req);if(typeof b.active!=='boolean')throw failure(400,'Invalid account status.');db.prepare('UPDATE users SET active=? WHERE id=?').run(b.active?1:0,target.id);if(!b.active)db.prepare('DELETE FROM sessions WHERE user_id=?').run(target.id);emit([...adminIds(),target.id]);return json(res,{ok:true})}
    if(path==='/api/email/retry'&&req.method==='POST'){requireAdmin(u);db.prepare("UPDATE email_outbox SET status='pending',attempts=0,next_attempt=0 WHERE status='failed'").run();return json(res,{ok:true})}
    throw failure(404,'This endpoint was not found.');
   }
   if(!isRead(req))throw failure(405,'Method not allowed.');
   const portalPath=path.startsWith('/portal/'),base=resolve(portalPath?config.publicDir:config.siteDir);let relative=decodeURIComponent(portalPath?path.slice(8):path);if(!relative||relative.endsWith('/'))relative+='index.html';const file=resolve(base,relative.replace(/^\/+/,''));if(!file.startsWith(base+sep))throw failure(404,'Page not found.');let actual=file;try{if((await stat(actual)).isDirectory())actual=resolve(actual,'index.html')}catch{if(path==='/'){res.writeHead(302,{Location:'/portal/'});res.end();return}throw failure(404,'Page not found.')}
   const data=await readFile(actual),type={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.svg':'image/svg+xml','.webp':'image/webp','.png':'image/png','.xml':'application/xml','.txt':'text/plain'}[extname(actual)]||'application/octet-stream';
   if(portalPath)res.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'; form-action 'self'");res.writeHead(200,{'Content-Type':type,'Cache-Control':portalPath?'no-store':'no-cache'});let output=data;if(!portalPath&&extname(actual)==='.html')output=Buffer.from(data.toString().replace('</body>','<script src="/portal/chat-widget.js" defer></script></body>'));res.end(req.method==='HEAD'?undefined:output)
  }catch(e){if(!res.headersSent){if(!e.status)console.error('Request failed:',e.message);json(res,{error:e.status?e.message:'Something went wrong. Please try again.'},e.status||500)}else res.end()}
 }
 const server=createServer(handle);const mailTimer=setInterval(async()=>{if(sending)return;sending=true;try{await deliver(db,config)}catch(e){console.error('Email queue unavailable:',e.message)}finally{sending=false}},15000);mailTimer.unref();
 const cleanup=setInterval(()=>{const t=Date.now();db.prepare('DELETE FROM sessions WHERE expires_at<?').run(t);db.prepare('DELETE FROM auth_tokens WHERE expires_at<?').run(t);db.prepare('DELETE FROM rate_limits WHERE reset_at<?').run(t-86400000)},3600000);cleanup.unref();
 return {server,db,close:()=>new Promise(resolve=>{clearInterval(mailTimer);clearInterval(cleanup);for(const l of listeners)l.res.end();server.close(()=>{db.close();resolve()});server.closeIdleConnections()})};
}
